name: Go CI (Windows)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20

    # Cache Go modules
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/AppData/Local/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    # Run tests
    - name: Run tests
      run: go test ./...

    # Build Windows executable
    - name: Build Windows executable
      run: go build -v -o game.exe ./...

    # Upload Windows build artifact
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: yavsc-game-windows
        path: ./yavsc-game.exe
